// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package protomsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	ID                   []byte      `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Vin                  []*TxInput  `protobuf:"bytes,2,rep,name=Vin,proto3" json:"Vin,omitempty"`
	Vount                []*TxOutput `protobuf:"bytes,3,rep,name=Vount,proto3" json:"Vount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *Transaction) GetVin() []*TxInput {
	if m != nil {
		return m.Vin
	}
	return nil
}

func (m *Transaction) GetVount() []*TxOutput {
	if m != nil {
		return m.Vount
	}
	return nil
}

type TxInput struct {
	Vout                 int64    `protobuf:"varint,1,opt,name=Vout,proto3" json:"Vout,omitempty"`
	TxID                 []byte   `protobuf:"bytes,2,opt,name=TxID,proto3" json:"TxID,omitempty"`
	PrevTxHash           []byte   `protobuf:"bytes,3,opt,name=PrevTxHash,proto3" json:"PrevTxHash,omitempty"`
	ScriptSig            string   `protobuf:"bytes,4,opt,name=ScriptSig,proto3" json:"ScriptSig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxInput) Reset()         { *m = TxInput{} }
func (m *TxInput) String() string { return proto.CompactTextString(m) }
func (*TxInput) ProtoMessage()    {}
func (*TxInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}

func (m *TxInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxInput.Unmarshal(m, b)
}
func (m *TxInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxInput.Marshal(b, m, deterministic)
}
func (m *TxInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxInput.Merge(m, src)
}
func (m *TxInput) XXX_Size() int {
	return xxx_messageInfo_TxInput.Size(m)
}
func (m *TxInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TxInput.DiscardUnknown(m)
}

var xxx_messageInfo_TxInput proto.InternalMessageInfo

func (m *TxInput) GetVout() int64 {
	if m != nil {
		return m.Vout
	}
	return 0
}

func (m *TxInput) GetTxID() []byte {
	if m != nil {
		return m.TxID
	}
	return nil
}

func (m *TxInput) GetPrevTxHash() []byte {
	if m != nil {
		return m.PrevTxHash
	}
	return nil
}

func (m *TxInput) GetScriptSig() string {
	if m != nil {
		return m.ScriptSig
	}
	return ""
}

type TxOutput struct {
	No                   int64    `protobuf:"varint,1,opt,name=No,proto3" json:"No,omitempty"`
	Value                float32  `protobuf:"fixed32,2,opt,name=Value,proto3" json:"Value,omitempty"`
	ScriptPubKey         string   `protobuf:"bytes,3,opt,name=ScriptPubKey,proto3" json:"ScriptPubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxOutput) Reset()         { *m = TxOutput{} }
func (m *TxOutput) String() string { return proto.CompactTextString(m) }
func (*TxOutput) ProtoMessage()    {}
func (*TxOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{2}
}

func (m *TxOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxOutput.Unmarshal(m, b)
}
func (m *TxOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxOutput.Marshal(b, m, deterministic)
}
func (m *TxOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxOutput.Merge(m, src)
}
func (m *TxOutput) XXX_Size() int {
	return xxx_messageInfo_TxOutput.Size(m)
}
func (m *TxOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_TxOutput.DiscardUnknown(m)
}

var xxx_messageInfo_TxOutput proto.InternalMessageInfo

func (m *TxOutput) GetNo() int64 {
	if m != nil {
		return m.No
	}
	return 0
}

func (m *TxOutput) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TxOutput) GetScriptPubKey() string {
	if m != nil {
		return m.ScriptPubKey
	}
	return ""
}

func init() {
	proto.RegisterType((*Transaction)(nil), "protomsg.Transaction")
	proto.RegisterType((*TxInput)(nil), "protomsg.TxInput")
	proto.RegisterType((*TxOutput)(nil), "protomsg.TxOutput")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xbd, 0x6a, 0xc3, 0x30,
	0x10, 0xc7, 0xb1, 0x94, 0xb4, 0xf1, 0x25, 0x14, 0x72, 0x74, 0xd0, 0x50, 0x8a, 0x71, 0x17, 0x4f,
	0x1e, 0xda, 0x57, 0xf0, 0x50, 0x53, 0x48, 0x83, 0x22, 0xbc, 0x3b, 0xc1, 0xa4, 0x86, 0x54, 0x32,
	0xf6, 0xa9, 0xb8, 0x6f, 0x5f, 0x74, 0x4e, 0x48, 0x3a, 0xe9, 0xf4, 0xff, 0xe0, 0x77, 0x07, 0x6b,
	0xea, 0x6b, 0x3b, 0xd4, 0x07, 0x6a, 0x9d, 0xcd, 0xbb, 0xde, 0x91, 0xc3, 0x05, 0x3f, 0xdf, 0xc3,
	0x31, 0x3d, 0xc1, 0xd2, 0x5c, 0x6d, 0x7c, 0x00, 0x51, 0x16, 0x2a, 0x4a, 0xa2, 0x6c, 0xa5, 0x45,
	0x59, 0xe0, 0x0b, 0xc8, 0xaa, 0xb5, 0x4a, 0x24, 0x32, 0x5b, 0xbe, 0xae, 0xf3, 0x4b, 0x2d, 0x37,
	0x63, 0x69, 0x3b, 0x4f, 0x3a, 0xb8, 0x98, 0xc1, 0xbc, 0x72, 0xde, 0x92, 0x92, 0x1c, 0xc3, 0xdb,
	0xd8, 0xa7, 0xa7, 0x90, 0x9b, 0x02, 0xa9, 0x83, 0xfb, 0x73, 0x13, 0x11, 0x66, 0x95, 0xf3, 0xc4,
	0x2c, 0xa9, 0x79, 0x0e, 0x9a, 0x19, 0xcb, 0x42, 0x09, 0xe6, 0xf3, 0x8c, 0xcf, 0x00, 0xdb, 0xbe,
	0xf9, 0x31, 0xe3, 0x7b, 0x3d, 0x7c, 0x29, 0xc9, 0xce, 0x8d, 0x82, 0x4f, 0x10, 0xef, 0x0e, 0x7d,
	0xdb, 0xd1, 0xae, 0x3d, 0xaa, 0x59, 0x12, 0x65, 0xb1, 0xbe, 0x0a, 0xa9, 0x81, 0xc5, 0x65, 0x87,
	0x70, 0xdb, 0xc6, 0x9d, 0x79, 0x62, 0xe3, 0xf0, 0x11, 0xe6, 0x55, 0x7d, 0xf2, 0x0d, 0xe3, 0x84,
	0x9e, 0x3e, 0x98, 0xc2, 0x6a, 0xaa, 0x6f, 0xfd, 0xfe, 0xa3, 0xf9, 0x65, 0x62, 0xac, 0xff, 0x69,
	0xfb, 0x3b, 0x3e, 0xf0, 0xed, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x6f, 0x7b, 0x91, 0x5a, 0x01,
	0x00, 0x00,
}
